//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.visit = new HashSet<visit>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string EmergencyContact { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
    
        public virtual ICollection<visit> visit { get; set; }
    }
}
