//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public int Id { get; set; }
        public int PatientType { get; set; }
        public int DoctorId { get; set; }
        public Nullable<int> BedId { get; set; }
        public System.DateTime DateOfVisit { get; set; }
        public Nullable<System.DateTime> DateOfDischarge { get; set; }
        public string Symptoms { get; set; }
        public string Disease { get; set; }
        public string Treatment { get; set; }
        public int PatientID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Bed Bed { get; set; }
    }
}
